blocks:
  - size
  - date
  - name

date: relative

ignore-globs:
  - .DS_Store
  - .git
  - .hushlogin
  - .CFUserTextEncoding
  
sorting:
  dir-grouping: first
  
symlink-arrow: ->

# total-size: true

icons:
  when: never
