add_newline = false # No new line at start
[line_break]
disabled = true # One line prompt
[character]
success_symbol = '[\$](bold green)' # Change symbol normally showed before command
error_symbol = '[\$](bold red)'
vicmd_symbol = '[\$](bold green)'
[directory]
read_only = ''
read_only_style = 'bold red'
